### ISSUE TITLE
Фідбек ДЗ 2 1 завдання

### ISSUE THREAD

**Issue by Kashoid23** [xiosky90/RubyHW#2]
Доволі не погано. Цікаве рішення з `take_while`

- [x] Оновіть будь ласка код за допомогою методів https://apidock.com/ruby/Integer/odd%3F та https://apidock.com/ruby/Array/reject
`arr.map { |v| v % 2 }`

- [x] #4
`arr.select { |v| (v % 2).zero? ? v : nil }`
`arr.select { |v| (v % 3).zero? ? v : nil }`

- [x] Передивіться як працює метод https://apidock.com/ruby/Array/min та оновіть рішення
`arr.sort.take(3)`

**Comment by oleksiimikhno** [comment]
Дякую, виправив
