### ISSUE TITLE
Feedback HW3 42 gem

### ISSUE THREAD

**Issue by LVALL** [xiosky90/RubyHW#5]
Все вірно!

Just FYI, є можливість зменшити кількість коду, шляхом розширення методів екземпляру в класі Integer напряму

```
# Gem extend Integer class
class Integer
  def forty_two?
    self == 42
  end
end
```
Працюватиме так само. Хоча, якби була необхідність додати більше власних методів, або вони були б складними, ваш підхід в такому випадку був би більш оптимальним.

**Comment by oleksiimikhno** [comment]
Дякую, за відповідь і роз'яснання. Виправив.
